name: Connect to L2TP VPN

on:
  - push

jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPN
        uses: ./.github/actions/l2tp-vpn
        with:
          VPN_GATEWAY: ${{ secrets.VPN_GATEWAY }}       # Set this in GitHub Secrets
          VPN_USER: ${{ secrets.VPN_USER }}             # Set this in GitHub Secrets
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}     # Set this in GitHub Secrets
          VPN_PSK: ${{ secrets.VPN_PSK }}               # Optional, set this in GitHub Secrets if required

