name: VPN Connection Setup

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  setup-vpn:
    runs-on: ubuntu-latest  # Ensure you're using a self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Necessary Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y network-manager-l2tp

      - name: Add L2TP VPN Connection
        run: |
          set -x  # Enable script debugging
          sudo nmcli connection add type vpn vpn-type l2tp con-name my-l2tp-vpn \
            --vpn-data "gateway=your.vpn.gateway; user=your_username; password-flags=0; ipsec-psk=your_ipsec_psk"
          # Replace `your.vpn.gateway`, `your_username`, and `your_ipsec_psk` with your actual VPN settings

      - name: Connect to VPN
        run: |
          set -x
          sudo nmcli connection up my-l2tp-vpn

      - name: Check VPN Connection Status
        run: |
          nmcli connection show --active
